std_msgs/Header header

string task_id

string STATUS_WAITING=Waiting
string STATUS_CALLING=Calling
string STATUS_ENTERING=Entering
string STATUS_RIDING=Riding
string STATUS_MOVING_MODEL=MovingModel
string STATUS_SWITCHING_MAP=SwitchingMap
string STATUS_RELOCALIZING=Relocalizing
string STATUS_FINISHED=Finished
string STATUS_FAILED=Failed
string STATUS_PAUSED=Paused
string STATUS_TERMINATED=Terminated

string elevator_status
string message
string operation
string from_floor
string target_floor
